# Generated by Django 4.2.3 on 2023-07-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_student_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
    ]
